var abrv_to_name = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District Of Columbia",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
  }

// var abrv_to_color = {
//     "AL": "#ACFF21",
//     "AK": "#AAFB25",
//     "AZ": "#A8F729",
//     "AR": "#A6F42E",
//     "CA": "#A4F032",
//     "CO": "#A2ED37",
//     "CT": "#A0E93B",
//     "DE": "#9EE540",
//     "DC": "#9CE244",
//     "FL": "#9ADE48",
//     "GA": "#98DB4D",
//     "HI": "#96D751",
//     "ID": "#94D456",
//     "IL": "#92D05A",
//     "IN": "#90CC5F",
//     "IA": "#8EC963",
//     "KS": "#8CC568",
//     "KY": "#8AC26C",
//     "LA": "#88BE70",
//     "ME": "#86BA75",
//     "MD": "#84B779",
//     "MA": "#82B37E",
//     "MI": "#80B082",
//     "MN": "#7EAC87",
//     "MS": "#7CA98B",
//     "MO": "#7BA590",
//     "MT": "#79A194",
//     "NE": "#779E98",
//     "NV": "#759A9D",
//     "NH": "#7397A1",
//     "NJ": "#7193A6",
//     "NM": "#6F90AA",
//     "NY": "#6D8CAF",
//     "NC": "#6B88B3",
//     "ND": "#6985B7",
//     "OH": "#6781BC",
//     "OK": "#657EC0",
//     "OR": "#637AC5",
//     "PA": "#6176C9",
//     "RI": "#5F73CE",
//     "SC": "#5D6FD2",
//     "SD": "#5B6CD7",
//     "TN": "#5968DB",
//     "TX": "#5765DF",
//     "UT": "#5561E4",
//     "VT": "#535DE8",
//     "VA": "#515AED",
//     "WA": "#4F56F1",
//     "WV": "#4D53F6",
//     "WI": "#4B4FFA",
//     "WY": "#4A4CFF"
//   }

var abrv_to_color = {
    "AL": "#FFFAC3",
    "AK": "#FEF9C4",
    "AZ": "#FDF8C5",
    "AR": "#FCF7C6",
    "CA": "#FBF7C7",
    "CO": "#FAF6C9",
    "CT": "#F9F5CA",
    "DE": "#F9F5CB",
    "DC": "#F8F4CC",
    "FL": "#F7F3CD",
    "GA": "#F6F3CF",
    "HI": "#F5F2D0",
    "ID": "#F4F1D1",
    "IL": "#F4F0D2",
    "IN": "#F3F0D3",
    "IA": "#F2EFD5",
    "KS": "#F1EED6",
    "KY": "#F0EED7",
    "LA": "#EFEDD8",
    "ME": "#EFECD9",
    "MD": "#EEECDB",
    "MA": "#EDEBDC",
    "MI": "#ECEADD",
    "MN": "#EBE9DE",
    "MS": "#EAE9DF",
    "MO": "#EAE8E1",
    "MT": "#E9E7E2",
    "NE": "#E8E7E3",
    "NV": "#E7E6E4",
    "NH": "#E6E5E5",
    "NJ": "#E5E5E7",
    "NM": "#E4E4E8",
    "NY": "#E4E3E9",
    "NC": "#E3E2EA",
    "ND": "#E2E2EB",
    "OH": "#E1E1ED",
    "OK": "#E0E0EE",
    "OR": "#DFE0EF",
    "PA": "#DFDFF0",
    "RI": "#DEDEF1",
    "SC": "#DDDEF3",
    "SD": "#DCDDF4",
    "TN": "#DBDCF5",
    "TX": "#DADBF6",
    "UT": "#DADBF7",
    "VT": "#D9DAF9",
    "VA": "#D8D9FA",
    "WA": "#D7D9FB",
    "WV": "#D6D8FC",
    "WI": "#D5D7FD",
    "WY": "#D5D7FF"
  }